apiVersion: apps/v1
kind: Deployment
metadata:
  name: laces-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laces-api
  template:
    metadata:
      labels:
        app: laces-api
    spec:
      containers:
      - name: laces-api
        image: nitrase/laces-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "lacesdb"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: laces-api
spec:
  selector:
    app: laces-api
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: laces-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laces-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
